frontoffice:
    resource: "@FrontofficeBundle/Resources/config/routing.yml"
    prefix:   /

backoffice:
    resource: "@BackofficeBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
