<?php

namespace BackofficeBundle\Repository;

/**
 * gerantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gerantRepository extends \Doctrine\ORM\EntityRepository
{
}
