<?php

namespace BackofficeBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ResponsablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableRepository extends \Doctrine\ORM\EntityRepository {

    public function ListeResponsables() {

        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT * FROM fos_user';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
    
    
    public function UnResponsableID($id) {

        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT * FROM fos_user WHERE id='.$id;
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
	
	
	public function ExisteResponsable($user,$email) {

        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT * FROM fos_user WHERE username like "'.$user.'" AND email like "'.$email.'"';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    

}
