<?php

namespace BackofficeBundle\Repository;

/**
 * sct_commercialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sct_commercialeRepository extends \Doctrine\ORM\EntityRepository
{
}
